### ISSUE TITLE
Mod is totally crashed.

### ISSUE THREAD

**Issue by yechingu** [ICodeMaster/CivilainTrade-CelestialWorkings#2]
[22:58:53][effect.cpp:380]: Script Error, attempted to execute an effect on an unsupported scope!
Event: tradelogic.1
Location:  file: events/icode_trader_logic.txt line: 148
Effect Type: random_owned_planet
Scope:type=fleet
id=441
random={ 48971174 48971174 }
saved_event_target={
	type=galactic_object
	id=835
	name="starting_star"

something got updated after 1.3.2 patch.
Steam done some sort of Ninja patch and after that patch now Stellaris Client is firing this error.
Some sort of change happend to game is breaking this MOD to death....

**Comment by ICodeMaster** [comment]
Thanks for the report will look into it

**Comment by ICodeMaster** [comment]
Issue is solved now, thanks again

**Comment by yechingu** [comment]
Always thanks for your valiant effort.

2016-11-22 1:54 GMT+09:00 ICodeMaster <notifications@github.com>:
